In [0]:
import pandas as pd

In [0]:
df = pd.read_csv("/Workspace/Users/saeedsoliman901@gmail.com/supply_chain_project/DataCoSupplyChainDataset.csv", encoding='ISO-8859-1')

In [0]:
#clean columns names
df.columns = [col.replace(' ', '_').replace('(', '').replace(')', '').replace('-', '_') for col in df.columns]

In [0]:
#clean data in columns
text_cols = ['Customer_City', 'Customer_Country', 'Order_City', 'Order_Country', 'Product_Name', 'Category_Name']
for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Type                         180519 non-null  object
 1   Days_for_shipping_real       180519 non-null  int64
 2   Days_for_shipment_scheduled  180519 non-null  int64
 3   Benefit_per_order            180519 non-null  float64
 4   Sales_per_customer           180519 non-null  float64
 5   Delivery_Status              180519 non-null  object
 6   Late_delivery_risk           180519 non-null  int64
 7   Category_Id                  180519 non-null  int64
 8   Category_Name                180519 non-null  object
 9   Customer_City                180519 non-null  object
 10  Customer_Country             180519 non-null  object
 11  Customer_Email               180519 non-null  object
 12  Customer_Fname               180519 non-null  object
 13  Customer_Id                  180519 non-null  int64
 14  Customer_Lname               180511 non-null  object
 15  Customer_Password            180519 non-null  object
 16  Customer_Segment             180519 non-null  object
 17  Customer_State               180519 non-null  object
 18  Customer_Street              180519 non-null  object
 19  Customer_Zipcode             180516 non-null  float64
 20  Department_Id                180519 non-null  int64
 21  Department_Name              180519 non-null  object
 22  Latitude                     180519 non-null  float64
 23  Longitude                    180519 non-null  float64
 24  Market                       180519 non-null  object
 25  Order_City                   180519 non-null  object
 26  Order_Country                180519 non-null  object
 27  Order_Customer_Id            180519 non-null  int64
 28  order_date_DateOrders        180519 non-null  object
 29  Order_Id                     180519 non-null  int64
 30  Order_Item_Cardprod_Id       180519 non-null  int64
 31  Order_Item_Discount          180519 non-null  float64
 32  Order_Item_Discount_Rate     180519 non-null  float64
 33  Order_Item_Id                180519 non-null  int64
 34  Order_Item_Product_Price     180519 non-null  float64
 35  Order_Item_Profit_Ratio      180519 non-null  float64
 36  Order_Item_Quantity          180519 non-null  int64
 37  Sales                        180519 non-null  float64
 38  Order_Item_Total             180519 non-null  float64
 39  Order_Profit_Per_Order       180519 non-null  float64
 40  Order_Region                 180519 non-null  object
 41  Order_State                  180519 non-null  object
 42  Order_Status                 180519 non-null  object
 43  Order_Zipcode                24840 non-null   float64
 44  Product_Card_Id              180519 non-null  int64
 45  Product_Category_Id          180519 non-null  int64
 46  Product_Description          0 non-null       float64
 47  Product_Image                180519 non-null  object
 48  Product_Name                 180519 non-null  object
 49  Product_Price                180519 non-null  float64
 50  Product_Status               180519 non-null  int64
 51  shipping_date_DateOrders     180519 non-null  object
 52  Shipping_Mode                180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [0]:
df.head(10)

       Type  Days_for_shipping_real  ...       order_date_dt    shipping_date_dt
0     DEBIT                       3  ... 2018-01-31 22:56:00 2018-02-03 22:56:00
1  TRANSFER                       5  ... 2018-01-13 12:27:00 2018-01-18 12:27:00
2      CASH                       4  ... 2018-01-13 12:06:00 2018-01-17 12:06:00
3     DEBIT                       3  ... 2018-01-13 11:45:00 2018-01-16 11:45:00
4   PAYMENT                       2  ... 2018-01-13 11:24:00 2018-01-15 11:24:00
5  TRANSFER                       6  ... 2018-01-13 11:03:00 2018-01-19 11:03:00
6     DEBIT                       2  ... 2018-01-13 10:42:00 2018-01-15 10:42:00
7  TRANSFER                       2  ... 2018-01-13 10:21:00 2018-01-15 10:21:00
8      CASH                       3  ... 2018-01-13 10:00:00 2018-01-16 10:00:00
9      CASH                       2  ... 2018-01-13 09:39:00 2018-01-15 09:39:00

[10 rows x 55 columns]

In [0]:

order_date_col = [c for c in df.columns if 'order_date' in c.lower()][0]
shipping_date_col = [c for c in df.columns if 'shipping_date' in c.lower()][0]

In [0]:
#transform order_date and shipping_date to datetime
df['order_date_dt'] = pd.to_datetime(df[order_date_col])
df['shipping_date_dt'] = pd.to_datetime(df[shipping_date_col])

In [0]:
#measure shipping gap between scheduled and real
df['Shipping_Gap'] = df['Days_for_shipping_real'] - df['Days_for_shipment_scheduled']

In [0]:
#drop columns
cols_to_drop = [
    'Product_Card_Id', 'Product_Image', 'Customer_Email', 'Customer_Password', 
    'Customer_Fname', 'Customer_Lname', 'Customer_Street', 'Customer_Zipcode',
    'Product_Description', 'Order_Zipcode', 'order_date_Date_Orders', 'shipping_date_Date_Orders'
]

In [0]:
# to skip errors
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

In [0]:
df.head(10)

       Type  Days_for_shipping_real  ...    shipping_date_dt  Shipping_Gap
0     DEBIT                       3  ... 2018-02-03 22:56:00            -1
1  TRANSFER                       5  ... 2018-01-18 12:27:00             1
2      CASH                       4  ... 2018-01-17 12:06:00             0
3     DEBIT                       3  ... 2018-01-16 11:45:00            -1
4   PAYMENT                       2  ... 2018-01-15 11:24:00            -2
5  TRANSFER                       6  ... 2018-01-19 11:03:00             2
6     DEBIT                       2  ... 2018-01-15 10:42:00             1
7  TRANSFER                       2  ... 2018-01-15 10:21:00             1
8      CASH                       3  ... 2018-01-16 10:00:00             1
9      CASH                       2  ... 2018-01-15 09:39:00             1

[10 rows x 46 columns]

In [0]:
#cheack df duplicated rows
df.duplicated().sum()

np.int64(0)

In [0]:
# delete duplicated vaukes if found and count the numbers of deleted rows
initial_count = len(df)
df.drop_duplicates(inplace=True)
dropped_duplicates = initial_count - len(df)

In [0]:
#check null values
df.isnull().sum()

Type                           0
Days_for_shipping_real         0
Days_for_shipment_scheduled    0
Benefit_per_order              0
Sales_per_customer             0
Delivery_Status                0
Late_delivery_risk             0
Category_Id                    0
Category_Name                  0
Customer_City                  0
Customer_Country               0
Customer_Id                    0
Customer_Segment               0
Customer_State                 0
Department_Id                  0
Department_Name                0
Latitude                       0
Longitude                      0
Market                         0
Order_City                     0
Order_Country                  0
Order_Customer_Id              0
order_date_DateOrders          0
Order_Id                       0
Order_Item_Cardprod_Id         0
Order_Item_Discount            0
Order_Item_Discount_Rate       0
Order_Item_Id                  0
Order_Item_Product_Price       0
Order_Item_Profit_Ratio        0
Order_Item_Quantity            0
Sales                          0
Order_Item_Total               0
Order_Profit_Per_Order         0
Order_Region                   0
Order_State                    0
Order_Status                   0
Product_Category_Id            0
Product_Name                   0
Product_Price                  0
Product_Status                 0
shipping_date_DateOrders       0
Shipping_Mode                  0
order_date_dt                  0
shipping_date_dt               0
Shipping_Gap                   0
dtype: int64

In [0]:
# make sure that sales is not negative values
df = df[df['Sales'] > 0]

In [0]:
spark_df = spark.createDataFrame(df)
spark_df.write.mode("overwrite").saveAsTable("workspace.default.dataco_cleaned_final")